export const milestoneTemplates: Record<string, string[]> = {
  Construction: [
    "Site preparation",
    "Foundation excavation",
    "Foundation pour",
    "Base structure",
    "Block laying",
    "Roofing structure",
    "Roof sheeting",
    "Window & door frames",
    "Electrical rough-in",
    "Plumbing rough-in",
    "Plastering",
    "Tiling",
    "Painting",
    "Finishing & fittings",
    "Handover",
  ],
  "Solar Installation": [
    "Site survey",
    "Equipment delivery",
    "Roof preparation",
    "Panel mounting",
    "Inverter installation",
    "Wiring & connections",
    "Battery installation",
    "Testing & commissioning",
    "Client training",
    "Handover",
  ],
  Landscaping: [
    "Site assessment",
    "Ground clearing",
    "Soil preparation",
    "Irrigation installation",
    "Planting",
    "Lawn installation",
    "Hardscaping",
    "Water features",
    "Final touches",
    "Maintenance handover",
  ],
  "Interior Design": [
    "Empty space",
    "Demolition",
    "Electrical & plumbing",
    "Flooring",
    "Walls & ceiling",
    "Cabinetry & built-ins",
    "Furniture installation",
    "Lighting",
    "Décor & finishing",
    "Reveal",
  ],
  Roofing: [
    "Existing roof inspection",
    "Existing roof removal",
    "Structural inspection",
    "Underlayment",
    "Tile or sheet installation",
    "Flashing & sealing",
    "Guttering",
    "Final inspection",
    "Handover",
  ],
  Electrical: [
    "Site assessment",
    "DB board installation",
    "Conduit installation",
    "Cable pulling",
    "Outlet & switch fitting",
    "Lighting installation",
    "Testing & certification",
    "Handover",
  ],
  Plumbing: [
    "Site assessment",
    "Pipe installation",
    "Geyser installation",
    "Fixture installation",
    "Pressure testing",
    "Final inspection",
    "Handover",
  ],
  Other: [
    "Planning",
    "Preparation",
    "Phase 1",
    "Phase 2",
    "Phase 3",
    "Finishing",
    "Completion",
    "Handover",
  ],
};

export function getTemplates(category: string): string[] {
  return milestoneTemplates[category] ?? milestoneTemplates["Other"]!;
}
