import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        layout: "1100px",
      },
      fontSize: {
        xs: ["11px", { lineHeight: "1.4" }],
        sm: ["13px", { lineHeight: "1.5" }],
        base: ["15px", { lineHeight: "1.55" }],
        lg: ["17px", { lineHeight: "1.4" }],
        xl: ["22px", { lineHeight: "1.3" }],
        "2xl": ["28px", { lineHeight: "1.2" }],
        "3xl": ["40px", { lineHeight: "1.1" }],
        "4xl": ["56px", { lineHeight: "1.05" }],
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["var(--font-inter)", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ["var(--font-inter)", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
        quotation: ["var(--font-quotation)", "Roboto", "sans-serif"],
      },
      colors: {
        segmiq: {
          navy: "var(--segmiq-navy, #06152E)",
          "deep-blue": "var(--segmiq-deep-blue, #0B1F49)",
          indigo: "var(--segmiq-indigo, #18245E)",
          violet: "var(--segmiq-violet, #38217A)",
          purple: "var(--segmiq-purple, #5B2BA8)",
          "soft-blue": "var(--segmiq-soft-blue, #3458A4)",
          lime: "var(--segmiq-lime, #D4FF4F)",
          "bg-950": "var(--segmiq-bg-950, #06152E)",
          "bg-900": "var(--segmiq-bg-900, #08142B)",
          blue: "var(--segmiq-blue, #3458A4)",
          text: "var(--segmiq-text, #ffffff)",
          muted: "var(--segmiq-muted, rgba(255,255,255,.48))",
          border: "var(--segmiq-border, rgba(255,255,255,.10))",
        },
        surface: {
          sidebar: "var(--surface-sidebar)",
          "sidebar-elevated": "var(--surface-sidebar-elevated)",
          "sidebar-border": "var(--surface-sidebar-border)",
          canvas: "var(--surface-canvas)",
          card: "var(--surface-card)",
          "card-alt": "var(--surface-card-alt)",
          overlay: "var(--surface-overlay)",
          input: "var(--surface-input)",
          modal: "var(--surface-modal)",
        },
        bg: {
          primary: "var(--bg-primary)",
          secondary: "var(--bg-secondary)",
          tertiary: "var(--bg-tertiary)",
          quaternary: "var(--bg-quaternary)",
        },
        ink: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          "on-dark": "var(--text-on-dark)",
          "on-dark-dim": "var(--text-on-dark-dim)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          ink: "var(--accent-ink)",
          foreground: "var(--accent-foreground)",
          fg: "var(--accent-fg)",
        },
        semantic: {
          success: "var(--success)",
          warning: "var(--warning)",
          danger: "var(--danger)",
          info: "var(--info)",
        },
        border: {
          DEFAULT: "var(--border)",
          strong: "var(--border-strong)",
          hover: "var(--border-hover)",
          focus: "var(--border-focus)",
          dark: "var(--border-dark)",
        },
        sales: {
          bg: "var(--sales-bg)",
          surface: "var(--sales-surface)",
          "surface-subtle": "var(--sales-surface-subtle)",
          "surface-hover": "var(--sales-surface-hover)",
          "surface-active": "var(--sales-surface-active)",
          "surface-raised": "var(--sales-surface-raised)",
          "surface-selected": "var(--sales-surface-selected)",
          "bg-subtle": "var(--sales-bg-subtle)",
          "text-primary": "var(--sales-text-primary)",
          "text-secondary": "var(--sales-text-secondary)",
          "text-muted": "var(--sales-text-muted)",
          "text-disabled": "var(--sales-text-disabled)",
          "text-label": "var(--sales-text-label)",
          border: "var(--sales-border)",
          "border-subtle": "var(--sales-border-subtle)",
          "border-strong": "var(--sales-border-strong)",
          brand: "var(--sales-brand)",
          "brand-hover": "var(--sales-brand-hover)",
          "brand-active": "var(--sales-brand-active)",
          ink: "var(--sales-ink)",
          "brand-soft": "var(--sales-brand-soft)",
          "brand-soft-solid": "var(--sales-brand-soft-solid)",
          "brand-border": "var(--sales-brand-border)",
          "brand-text": "var(--sales-brand-text)",
          "brand-fg": "var(--sales-brand-fg)",
          "neutral-100": "var(--sales-neutral-100)",
          "neutral-200": "var(--sales-neutral-200)",
          "neutral-300": "var(--sales-neutral-300)",
          success: "var(--sales-success)",
          "success-soft": "var(--sales-success-soft)",
          "success-fg": "var(--sales-success-fg)",
          warning: "var(--sales-warning)",
          "warning-soft": "var(--sales-warning-soft)",
          "warning-fg": "var(--sales-warning-fg)",
          danger: "var(--sales-danger)",
          "danger-soft": "var(--sales-danger-soft)",
          "danger-fg": "var(--sales-danger-fg)",
          info: "var(--sales-info)",
          "info-soft": "var(--sales-info-soft)",
          "info-fg": "var(--sales-info-fg)",
          purple: "var(--sales-purple)",
          "purple-soft": "var(--sales-purple-soft)",
          "purple-fg": "var(--sales-purple-fg)",
          teal: "var(--sales-teal)",
          "teal-soft": "var(--sales-teal-soft)",
          "teal-fg": "var(--sales-teal-fg)",
          cyan: "var(--sales-cyan)",
          "cyan-soft": "var(--sales-cyan-soft)",
          "cyan-fg": "var(--sales-cyan-fg)",
          orange: "var(--sales-orange)",
          "orange-soft": "var(--sales-orange-soft)",
          "orange-fg": "var(--sales-orange-fg)",
          whatsapp: "var(--sales-whatsapp)",
          "table-header": "var(--sales-table-header-bg)",
          "table-hover": "var(--sales-table-hover)",
          "table-selected": "var(--sales-table-selected)",
        },
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "sales-xs": "var(--sales-radius-xs)",
        "sales-sm": "var(--sales-radius-sm)",
        "sales-md": "var(--sales-radius-md)",
        "sales-lg": "var(--sales-radius-lg)",
        "sales-xl": "var(--sales-radius-xl)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        "sales-card": "var(--sales-shadow-card)",
        "sales-btn": "var(--sales-btn-shadow)",
        "sales-btn-hover": "var(--sales-btn-shadow-hover)",
        "sales-btn-active": "var(--sales-btn-shadow-active)",
        "sales-card-hover": "var(--sales-shadow-card-hover)",
        "sales-raised": "var(--sales-shadow-raised)",
        "sales-dropdown": "var(--sales-shadow-dropdown)",
        "sales-popover": "var(--sales-shadow-popover)",
        "sales-modal": "var(--sales-shadow-modal)",
        "sales-focus": "var(--sales-focus-ring)",
      },
      letterSpacing: {
        display: "-0.02em",
      },
      keyframes: {
        ticker: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        ticker: "ticker 40s linear infinite",
      },
    },
  },
  plugins: [],
};
export default config;
