import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        layout: "1100px",
      },
      fontSize: {
        xs: ["11px", { lineHeight: "1.4" }],
        sm: ["13px", { lineHeight: "1.5" }],
        base: ["15px", { lineHeight: "1.55" }],
        lg: ["17px", { lineHeight: "1.4" }],
        xl: ["22px", { lineHeight: "1.3" }],
        "2xl": ["28px", { lineHeight: "1.2" }],
        "3xl": ["40px", { lineHeight: "1.1" }],
        "4xl": ["56px", { lineHeight: "1.05" }],
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        display: ["var(--font-instrument-serif)", "ui-serif", "Georgia", "serif"],
        serif: ["var(--font-instrument-serif)", "ui-serif", "Georgia", "serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
      },
      colors: {
        surface: {
          sidebar: "var(--surface-sidebar)",
          "sidebar-elevated": "var(--surface-sidebar-elevated)",
          "sidebar-border": "var(--surface-sidebar-border)",
          canvas: "var(--surface-canvas)",
          card: "var(--surface-card)",
          "card-alt": "var(--surface-card-alt)",
          overlay: "var(--surface-overlay)",
          input: "var(--surface-input)",
          modal: "var(--surface-modal)",
        },
        bg: {
          primary: "var(--bg-primary)",
          secondary: "var(--bg-secondary)",
          tertiary: "var(--bg-tertiary)",
          quaternary: "var(--bg-quaternary)",
        },
        ink: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          "on-dark": "var(--text-on-dark)",
          "on-dark-dim": "var(--text-on-dark-dim)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          ink: "var(--accent-ink)",
          foreground: "var(--accent-foreground)",
          fg: "var(--accent-fg)",
        },
        semantic: {
          success: "var(--success)",
          warning: "var(--warning)",
          danger: "var(--danger)",
          info: "var(--info)",
        },
        border: {
          DEFAULT: "var(--border)",
          strong: "var(--border-strong)",
          hover: "var(--border-hover)",
          focus: "var(--border-focus)",
          dark: "var(--border-dark)",
        },
        sales: {
          bg: "var(--sales-bg)",
          surface: "var(--sales-surface)",
          "surface-subtle": "var(--sales-surface-subtle)",
          "surface-hover": "var(--sales-surface-hover)",
          "surface-active": "var(--sales-surface-active)",
          "text-primary": "var(--sales-text-primary)",
          "text-secondary": "var(--sales-text-secondary)",
          "text-muted": "var(--sales-text-muted)",
          "text-disabled": "var(--sales-text-disabled)",
          border: "var(--sales-border)",
          "border-subtle": "var(--sales-border-subtle)",
          "border-strong": "var(--sales-border-strong)",
          brand: "var(--sales-brand)",
          "brand-hover": "var(--sales-brand-hover)",
          "brand-soft": "var(--sales-brand-soft)",
          "brand-border": "var(--sales-brand-border)",
          "brand-text": "var(--sales-brand-text)",
          "brand-fg": "var(--sales-brand-fg)",
          success: "var(--sales-success)",
          "success-soft": "var(--sales-success-soft)",
          warning: "var(--sales-warning)",
          "warning-soft": "var(--sales-warning-soft)",
          danger: "var(--sales-danger)",
          "danger-soft": "var(--sales-danger-soft)",
          info: "var(--sales-info)",
          "info-soft": "var(--sales-info-soft)",
          purple: "var(--sales-purple)",
          "purple-soft": "var(--sales-purple-soft)",
          teal: "var(--sales-teal)",
          "teal-soft": "var(--sales-teal-soft)",
          whatsapp: "var(--sales-whatsapp)",
        },
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "sales-xs": "var(--sales-radius-xs)",
        "sales-sm": "var(--sales-radius-sm)",
        "sales-md": "var(--sales-radius-md)",
        "sales-lg": "var(--sales-radius-lg)",
        "sales-xl": "var(--sales-radius-xl)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        "sales-card": "var(--sales-shadow-card)",
        "sales-dropdown": "var(--sales-shadow-dropdown)",
        "sales-popover": "var(--sales-shadow-popover)",
        "sales-modal": "var(--sales-shadow-modal)",
      },
      letterSpacing: {
        display: "-0.02em",
      },
      keyframes: {
        ticker: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        ticker: "ticker 40s linear infinite",
      },
    },
  },
  plugins: [],
};
export default config;
