import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";
import { formatMoney } from "@/lib/quotations/totals";
import type { ComparedMetric, FunnelStageResult, WeeklyReportPayload } from "./types";

const INK = "#0C0C0C";
const MUTED = "#6B6B6B";
const LINE = "#E6E6E4";
const PAPER = "#FFFFFF";
const BAND = "#F6F6F3";
const LIME = "#D4FF4F";
const LIME_SOFT = "#EEF6C8";

const styles = StyleSheet.create({
  page: {
    paddingTop: 52,
    paddingBottom: 58,
    paddingHorizontal: 42,
    fontSize: 9.5,
    fontFamily: "Helvetica",
    color: INK,
    backgroundColor: PAPER,
  },
  coverPage: {
    paddingTop: 64,
    paddingBottom: 52,
    paddingHorizontal: 48,
    fontFamily: "Helvetica",
    color: INK,
    backgroundColor: PAPER,
  },
  limeBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 5,
    backgroundColor: LIME,
  },
  motif: {
    position: "absolute",
    right: 36,
    bottom: 72,
    width: 118,
    height: 118,
    borderWidth: 1,
    borderColor: LIME_SOFT,
  },
  motifInner: {
    margin: 18,
    flex: 1,
    borderWidth: 1,
    borderColor: LIME,
  },
  header: {
    position: "absolute",
    top: 20,
    left: 42,
    right: 42,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: MUTED,
  },
  footer: {
    position: "absolute",
    bottom: 22,
    left: 42,
    right: 42,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: MUTED,
    borderTopWidth: 0.6,
    borderTopColor: LINE,
    paddingTop: 8,
  },
  coverBrand: { flexDirection: "row", alignItems: "center", marginBottom: 36 },
  logo: { width: 40, height: 40, objectFit: "contain", marginRight: 12 },
  orgName: { fontSize: 13, fontWeight: 700 },
  kicker: { fontSize: 8, color: MUTED, marginTop: 3, letterSpacing: 1.1, textTransform: "uppercase" },
  title: { fontSize: 24, fontWeight: 700, marginTop: 18, lineHeight: 1.25 },
  meta: { marginTop: 18, color: MUTED, lineHeight: 1.6, fontSize: 10 },
  prepared: { marginTop: 36, fontSize: 9, color: MUTED },
  h2: { fontSize: 13, fontWeight: 700, marginBottom: 8, marginTop: 4 },
  h3: { fontSize: 10, fontWeight: 700, marginBottom: 4, marginTop: 8 },
  p: { fontSize: 9.5, lineHeight: 1.5, marginBottom: 8 },
  muted: { color: MUTED },
  insight: { width: "48%", paddingTop: 8, borderTopWidth: 0.8, borderTopColor: LINE },
  insightLabel: { fontSize: 7.5, color: MUTED, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 4 },
  tableHeader: { flexDirection: "row", backgroundColor: BAND, paddingVertical: 6, paddingHorizontal: 6 },
  tableRow: { flexDirection: "row", paddingVertical: 6, paddingHorizontal: 6, borderBottomWidth: 0.5, borderBottomColor: LINE },
  th: { fontSize: 7.5, color: MUTED, textTransform: "uppercase", letterSpacing: 0.4, fontWeight: 700 },
  cell: { fontSize: 9 },
  barTrack: { height: 6, backgroundColor: BAND, borderRadius: 3, marginTop: 3 },
  barFill: { height: 6, backgroundColor: INK, borderRadius: 3 },
  callout: { backgroundColor: BAND, padding: 10, marginTop: 10, marginBottom: 8 },
  warning: { borderLeftWidth: 2, borderLeftColor: "#C4A35A", paddingLeft: 8, marginTop: 8, marginBottom: 10 },
  bullet: { marginBottom: 5, paddingLeft: 2 },
  recNum: { width: 22, fontSize: 9, color: MUTED },
  recBody: { flex: 1 },
});

function formatMetric(metric: ComparedMetric, currency: string): string {
  if (metric.current == null) return "n/a";
  if (metric.format === "money") return formatMoney(metric.current, currency);
  if (metric.format === "minutes") {
    const mins = metric.current;
    if (mins < 60) return `${Math.round(mins)} min`;
    return `${(mins / 60).toFixed(1)} h`;
  }
  if (metric.format === "percent") return `${metric.current}%`;
  return String(Math.round(metric.current));
}

function Header({ org, period }: { org: string; period: string }) {
  return (
    <View style={styles.header} fixed>
      <Text>
        {org} · Weekly Sales Performance Report
      </Text>
      <Text>{period} · SegmiQ</Text>
    </View>
  );
}

function Footer({ org }: { org: string }) {
  return (
    <View style={styles.footer} fixed>
      <Text>Confidential · {org}</Text>
      <Text>Generated by SegmiQ</Text>
      <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
    </View>
  );
}

function metricById(metrics: ComparedMetric[], id: string) {
  return metrics.find((metric) => metric.id === id);
}

function funnelDropLabel(funnel: FunnelStageResult[]): string | null {
  let best: FunnelStageResult | null = null;
  for (let i = 1; i < funnel.length; i++) {
    const row = funnel[i]!;
    if (!best || row.dropOff > best.dropOff) best = row;
  }
  if (!best || best.dropOff <= 0) return null;
  const index = funnel.findIndex((stage) => stage.id === best!.id);
  const from = index > 0 ? funnel[index - 1] : null;
  const label = from ? `${from.label} → ${best.label}` : best.label;
  return `${label}. ${best.dropOff} did not progress.`;
}

export function WeeklyTeamReportDocument({
  payload,
  logoDataUri,
}: {
  payload: WeeklyReportPayload;
  logoDataUri: string | null;
}) {
  const { cover, ai, metrics, funnel, salespeople, attention, lostDeals, conversation, pipelineHealth } = payload;
  const maxFunnel = Math.max(...funnel.map((s) => s.count), 1);
  const highlightIds = ["new_leads", "deals_won", "revenue_won", "avg_first_response", "follow_ups_missed", "quotations_sent"];
  const highlight = highlightIds.map((id) => metricById(metrics, id)).filter(Boolean) as ComparedMetric[];
  const pipelineTotal = pipelineHealth.reduce((sum, bucket) => sum + bucket.value, 0);
  const dropLabel = funnelDropLabel(funnel);
  const maxLost = Math.max(...lostDeals.reasonCounts.map((row) => row.count), 1);

  return (
    <Document title={`${cover.title} · ${cover.periodLabel}`} author="SegmiQ Intelligence">
      <Page size="A4" style={styles.coverPage}>
        <View style={styles.limeBar} />
        <View style={styles.motif}>
          <View style={styles.motifInner} />
        </View>
        <View style={styles.coverBrand}>
          {logoDataUri ? <Image style={styles.logo} src={logoDataUri} /> : null}
          <View>
            <Text style={styles.orgName}>{cover.organisationName}</Text>
            <Text style={styles.kicker}>SegmiQ Intelligence</Text>
          </View>
        </View>
        <Text style={styles.title}>{cover.title}</Text>
        <Text style={styles.meta}>
          {cover.periodLabel}
          {"\n"}Generated {cover.generatedAtLabel}
          {"\n"}Timezone {cover.timezone}
        </Text>
        <Text style={styles.prepared}>{cover.preparedBy}</Text>
        {payload.lowData ? (
          <View style={styles.callout}>
            <Text style={styles.p}>{ai.dataSufficiencyNote}</Text>
          </View>
        ) : null}
        <Footer org={cover.organisationName} />
      </Page>

      <Page size="A4" style={styles.page}>
        <Header org={cover.organisationName} period={cover.periodLabel} />
        <Footer org={cover.organisationName} />
        <Text style={styles.h2}>Executive summary</Text>
        <Text style={styles.p}>{ai.executiveSummary}</Text>
        <View style={{ flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between" }}>
          <View style={styles.insight}>
            <Text style={styles.insightLabel}>What went well</Text>
            <Text style={styles.p}>{ai.whatWentWell}</Text>
          </View>
          <View style={styles.insight}>
            <Text style={styles.insightLabel}>Where momentum was lost</Text>
            <Text style={styles.p}>{ai.whereMomentumWasLost}</Text>
          </View>
          <View style={styles.insight}>
            <Text style={styles.insightLabel}>Biggest risk</Text>
            <Text style={styles.p}>{ai.biggestRisk}</Text>
          </View>
          <View style={styles.insight}>
            <Text style={styles.insightLabel}>Priority for next week</Text>
            <Text style={styles.p}>{ai.priorityForNextWeek}</Text>
          </View>
        </View>
      </Page>

      <Page size="A4" style={styles.page}>
        <Header org={cover.organisationName} period={cover.periodLabel} />
        <Footer org={cover.organisationName} />
        <Text style={styles.h2}>Team performance</Text>
        <View style={styles.tableHeader}>
          <Text style={[styles.th, { width: "34%" }]}>Metric</Text>
          <Text style={[styles.th, { width: "22%" }]}>This week</Text>
          <Text style={[styles.th, { width: "44%" }]}>Compared with last week</Text>
        </View>
        {highlight.map((metric) => (
          <View key={metric.id} style={styles.tableRow} wrap={false}>
            <Text style={[styles.cell, { width: "34%" }]}>{metric.label}</Text>
            <Text style={[styles.cell, { width: "22%" }]}>{formatMetric(metric, cover.currency)}</Text>
            <Text style={[styles.cell, { width: "44%", color: MUTED }]}>{metric.trend.label}</Text>
          </View>
        ))}

        <Text style={[styles.h2, { marginTop: 18 }]}>Sales funnel</Text>
        {funnel.map((stage, index) => (
          <View key={stage.id} wrap={false} style={{ marginBottom: 8 }}>
            <Text>
              {stage.label}: {stage.count}
              {index > 0 ? `  · ${stage.conversionPct}% from previous` : ""}
              {stage.dropOff > 0 ? `  · drop-off ${stage.dropOff}` : ""}
            </Text>
            <View style={styles.barTrack}>
              <View style={[styles.barFill, { width: `${Math.max(4, (stage.count / maxFunnel) * 100)}%` }]} />
            </View>
          </View>
        ))}
        {dropLabel ? (
          <View style={styles.warning}>
            <Text style={{ fontWeight: 700, marginBottom: 3 }}>Largest drop-off</Text>
            <Text>{dropLabel}</Text>
          </View>
        ) : null}
        {payload.funnelExplanation.map((insight, i) => (
          <Text key={i} style={styles.p}>
            {insight.kind === "interpretation" ? "SegmiQ analysis. " : ""}
            {insight.text}
          </Text>
        ))}
      </Page>

      <Page size="A4" style={styles.page}>
        <Header org={cover.organisationName} period={cover.periodLabel} />
        <Footer org={cover.organisationName} />
        <Text style={styles.h2}>Pipeline health</Text>
        <Text style={styles.p}>{formatMoney(pipelineTotal, cover.currency)} active pipeline</Text>
        <View style={{ flexDirection: "row", height: 8, backgroundColor: BAND, marginBottom: 10 }}>
          {pipelineHealth.map((bucket) => (
            <View
              key={bucket.id}
              style={{
                width: `${Math.max(bucket.pct, bucket.count > 0 ? 2 : 0)}%`,
                backgroundColor:
                  bucket.id === "healthy" ? INK : bucket.id === "needs_attention" ? "#C4A35A" : bucket.id === "quoted_awaiting_followup" ? LIME : "#8A6A4B",
              }}
            />
          ))}
        </View>
        {pipelineHealth.map((bucket) => (
          <Text key={bucket.id} style={styles.bullet}>
            {bucket.label}: {bucket.count} · {formatMoney(bucket.value, cover.currency)} · {bucket.pct}%
          </Text>
        ))}
        <Text style={styles.p}>{payload.pipelineHealthNarrative}</Text>

        <Text style={styles.h2}>Needs management attention</Text>
        {attention.length === 0 ? (
          <Text style={styles.p}>No major opportunities require management attention this week.</Text>
        ) : (
          attention.slice(0, 12).map((item) => (
            <View key={item.id} wrap={false} style={{ marginBottom: 9 }}>
              <Text style={{ fontWeight: 700 }}>
                {item.displayName}
                {item.value ? ` · ${formatMoney(item.value, cover.currency)}` : ""}
              </Text>
              <Text style={styles.muted}>
                {item.salespersonName ?? "Unassigned"} · {item.stageLabel}
                {item.daysInactive != null ? ` · ${item.daysInactive}d inactive` : ""}
              </Text>
              <Text>{item.reason}</Text>
              <Text>Recommended: {item.recommendedAction}</Text>
            </View>
          ))
        )}
      </Page>

      <Page size="A4" style={styles.page}>
        <Header org={cover.organisationName} period={cover.periodLabel} />
        <Footer org={cover.organisationName} />
        <Text style={styles.h2}>Sales team</Text>
        <View style={styles.tableHeader}>
          <Text style={[styles.th, { width: "28%" }]}>Name</Text>
          <Text style={[styles.th, { width: "44%" }]}>Observation</Text>
          <Text style={[styles.th, { width: "28%" }]}>Coaching focus</Text>
        </View>
        {salespeople.length === 0 ? (
          <Text style={styles.p}>No salespeople were in this organisation's team for the week.</Text>
        ) : (
          salespeople.map((person) => (
            <View key={person.salespersonId} wrap={false} style={styles.tableRow}>
              <Text style={[styles.cell, { width: "28%" }]}>{person.name}</Text>
              <Text style={[styles.cell, { width: "44%" }]}>{person.narrative}</Text>
              <Text style={[styles.cell, { width: "28%" }]}>{person.coachingFocus}</Text>
            </View>
          ))
        )}

        <Text style={[styles.h2, { marginTop: 16 }]}>What customers are telling your team</Text>
        {conversation.length === 0 ? (
          <Text style={styles.p}>No recurring conversation patterns were identified from authorised inbound messages.</Text>
        ) : (
          conversation.map((row) => (
            <Text key={row.id} style={styles.p}>
              {row.label}: {row.count} conversations. {row.interpretation}
            </Text>
          ))
        )}

        <Text style={styles.h2}>Lost deals</Text>
        {lostDeals.count === 0 ? (
          <Text style={styles.p}>No opportunities were marked lost this week.</Text>
        ) : (
          <>
            <Text style={styles.p}>
              {lostDeals.count} lost · {formatMoney(lostDeals.value, cover.currency)} potential revenue
            </Text>
            {lostDeals.reasonCounts.map((row) => (
              <View key={row.reason} wrap={false} style={{ marginBottom: 6 }}>
                <Text>
                  {row.reason}: {row.count}
                </Text>
                <View style={styles.barTrack}>
                  <View style={[styles.barFill, { width: `${(row.count / maxLost) * 100}%` }]} />
                </View>
              </View>
            ))}
            {lostDeals.narrative ? <Text style={styles.p}>SegmiQ analysis. {lostDeals.narrative}</Text> : null}
          </>
        )}
      </Page>

      <Page size="A4" style={styles.page}>
        <Header org={cover.organisationName} period={cover.periodLabel} />
        <Footer org={cover.organisationName} />
        <Text style={styles.h2}>Recommended actions</Text>
        {ai.managerRecommendations.length === 0 ? (
          <Text style={styles.p}>No additional management actions were required from this week's data.</Text>
        ) : (
          ai.managerRecommendations.map((row, i) => (
            <View key={i} wrap={false} style={{ flexDirection: "row", marginBottom: 10 }}>
              <Text style={styles.recNum}>{String(i + 1).padStart(2, "0")}</Text>
              <View style={styles.recBody}>
                <Text style={{ fontWeight: 700, marginBottom: 3 }}>{row.title}</Text>
                <Text>Evidence. {row.evidence}</Text>
                <Text>Recommended action. {row.action}</Text>
                <Text style={styles.muted}>Objective. {row.objective}</Text>
              </View>
            </View>
          ))
        )}

        <Text style={[styles.h2, { marginTop: 12 }]}>Priorities for next week</Text>
        {ai.nextWeekPriorities.length === 0 ? (
          <Text style={styles.p}>Keep the current operating cadence and review high-value pipeline in the weekly meeting.</Text>
        ) : (
          ai.nextWeekPriorities.map((row, i) => (
            <Text key={i} style={styles.bullet}>
              {String(i + 1).padStart(2, "0")}  {row.title} · {row.affectedCount} items
              {row.pipelineValue ? ` · ${formatMoney(row.pipelineValue, cover.currency)}` : ""} · {row.ownerLabel}
            </Text>
          ))
        )}

        <Text style={[styles.h2, { marginTop: 12 }]}>Suggested sales meeting agenda</Text>
        {ai.meetingAgenda.map((item, i) => (
          <Text key={i} style={styles.bullet}>
            {i + 1}. {item}
          </Text>
        ))}
      </Page>
    </Document>
  );
}
