import { BRAIN_SETTINGS_DEFAULTS, type CompanyBrainSnapshot } from "@/lib/company-brain/types";
import { demoIso, daysAgo } from "@/lib/demo/dates";
import { demoId } from "@/lib/demo/ids";

/** Demo business context for Rossi Tyres. Not imported from a real customer. */
export function rossiCompanyBrain(clientId: string, now = new Date()): CompanyBrainSnapshot {
  const at = demoIso(daysAgo(30, now));
  return {
    exists: true,
    settings: {
      ...BRAIN_SETTINGS_DEFAULTS,
      clientId,
      tradingName: "Rossi Tyres",
      businessKind: "dealership",
      customerModel: "BOTH",
      agentBusinessExplanation:
        "Demo business context. Tyre retail and fleet supply for individual motorists, fleet operators, construction companies, and logistics businesses. Common enquiries: tyre availability, sizes, brand comparison, pricing, fleet quotations, fitment, wheel alignment, and balancing. Demonstration prices are not official Rossi Tyres pricing.",
      primaryOffering: "Tyres, fitment, balancing, and wheel alignment",
      catalogueCustomerType: "Retail motorists and fleet buyers",
      typicalOrderType: "Sets of four for retail; multi-unit quotes for fleets",
      pricingGuidance: "Use the demonstration catalogue. Do not describe prices as official Rossi Tyres list prices.",
      neverEstimatePrices: false,
      voicePrimary: "warm",
      voiceSecondary: "direct",
      greetingStyle: "Use the customer's first name.",
      claimsToAvoid: ["Official Rossi price list", "Guaranteed same-day nationwide delivery"],
      createdAt: at,
      updatedAt: at,
    },
    idealCustomers: [
      {
        id: demoId("rossi:brain:retail"),
        name: "Individual motorist",
        description: "Car, bakkie, or SUV owner asking about a size or a set of four.",
        typicalRequirements: "Size, quantity, terrain, and whether fitment is needed.",
        minProjectSize: null,
        typicalDecisionMaker: "The driver",
        primaryInterest: "Availability and price",
        geographicRequirements: "Harare and nearby towns",
        goodFitIndicators: "Knows the tyre size or the vehicle",
        poorFitIndicators: null,
        disqualifyingConditions: null,
        sortOrder: 1,
        active: true,
      },
      {
        id: demoId("rossi:brain:fleet"),
        name: "Fleet operator",
        description: "Logistics, construction, or distribution company buying commercial tyres.",
        typicalRequirements: "Quantity, size, delivery date, and who approves the purchase.",
        minProjectSize: "Usually more than eight tyres",
        typicalDecisionMaker: "Procurement or fleet manager",
        primaryInterest: "Fleet quotation and delivery",
        geographicRequirements: "Harare industrial areas",
        goodFitIndicators: "Named company and a delivery window",
        poorFitIndicators: null,
        disqualifyingConditions: null,
        sortOrder: 2,
        active: true,
      },
    ],
    playbooks: [],
    stageGuidance: [],
    serviceAreas: [
      {
        id: demoId("rossi:brain:harare"),
        label: "Harare",
        country: "Zimbabwe",
        province: "Harare",
        city: "Harare",
        region: null,
        radiusKm: 40,
        serviceCategory: "Fitment",
        status: "PRIMARY",
        travelChargeApplies: false,
        travelChargeNote: null,
        minOrder: null,
        managerConfirmationRequired: false,
        assignedNote: "Demo service area",
        active: true,
      },
    ],
    appointmentTypes: [],
    faqs: [
      {
        id: demoId("rossi:brain:faq-size"),
        question: "Which size fits a Toyota Hilux GD6?",
        approvedAnswer: "A common size is 265/70R16. Confirm the size on the sidewall before quoting.",
        aliases: ["hilux size", "265/70R16"],
        category: "PRODUCT",
        active: true,
        productIds: [],
        lastReviewedAt: at,
        reviewerId: null,
        version: 1,
        updatedAt: at,
      },
    ],
    examples: [],
    rules: [],
    escalationRules: [],
    knowledgeDocuments: [],
    canonical: {
      companyName: "Rossi Tyres",
      industry: "Tyres / automotive",
      timezone: "Africa/Harare",
      website: null,
      phone: null,
      email: null,
      address: "Harare",
      country: "Zimbabwe",
      productCount: 24,
      serviceCount: 1,
      packageCount: 0,
      quoteTemplateCount: 0,
      currency: "USD",
      paymentTerms: null,
      allowQuotationDiscount: true,
      priceEditPolicy: null,
      hasOperatingHoursRow: true,
      workingDays: [1, 2, 3, 4, 5, 6],
      workStartTime: "08:00",
      workEndTime: "17:00",
      hasQualificationFlow: false,
      teamUserCount: 4,
      agentAutonomyMode: null,
      quoteAutoSendLimit: null,
    },
  };
}
