import type {
  CompanyBrainSettings,
  CompanyBrainSnapshot,
  IdealCustomer,
  QualificationPlaybook,
  ServiceArea,
} from "./types";
import { BRAIN_SETTINGS_DEFAULTS } from "./types";

/**
 * In-memory solar wholesaler fixture for tests. Never used as a production default.
 */
export function solarWholesalerFixture(clientId = "test-solar-wholesale"): CompanyBrainSnapshot {
  const settings: CompanyBrainSettings = {
    clientId,
    ...BRAIN_SETTINGS_DEFAULTS,
    tradingName: "SunGrid Wholesale",
    businessKind: "wholesaler",
    customerModel: "B2B",
    agentBusinessExplanation:
      "We supply solar equipment to installers and dealers. We sell solar panels, inverters, batteries and mounting systems. We are primarily a wholesale supplier and do not provide residential installations.",
    primaryOffering: "Wholesale solar equipment",
    catalogueCustomerType: "Solar installers and dealers",
    typicalOrderType: "Wholesale / project supply",
    weDoNotNormallySell: "Single retail panels to private homeowners",
    specialSellingConditions: "Bulk pricing depends on quantities",
    pricingGuidance: "Never provide estimated pricing if no current catalogue price exists. Do not describe prices as negotiable.",
    paymentGuidance: "Standard terms are upfront / company policy. Non-standard structures need manager review.",
    neverEstimatePrices: true,
    creditOffered: false,
    paymentPlansOffered: false,
    supportOffered: true,
    supportDestinationType: "SUPPORT_QUEUE",
    supportCategories: ["Product fault", "Warranty claim", "Technical question", "Delivery issue"],
    autonomousTroubleshooting: false,
    warrantyBoundaries: "Product warranty only. We do not honour installer workmanship claims.",
    voicePrimary: "professional",
    voiceSecondary: "direct",
    responseLength: "short",
    emojiPolicy: "none",
    claimsToAvoid: ["Do not call us the cheapest.", "Do not guarantee same-day delivery."],
    defaultEscalationMessage:
      "I want to make sure this is handled correctly, so I'm bringing a member of the team into the conversation.",
  };

  const customers: IdealCustomer[] = [
    {
      id: "ic-1",
      name: "Solar installer",
      description: "Licensed installers buying wholesale equipment",
      typicalRequirements: "Inverters, panels, batteries in project quantities",
      minProjectSize: "Dealer account / bulk order",
      typicalDecisionMaker: "Owner or procurement",
      primaryInterest: "Hybrid inverters and storage",
      geographicRequirements: "Zimbabwe",
      goodFitIndicators: "Trade account, repeat orders, installer licence",
      poorFitIndicators: "Homeowner wanting a single panel installed",
      disqualifyingConditions: null,
      sortOrder: 0,
      active: true,
    },
  ];

  const playbooks: QualificationPlaybook[] = [
    {
      id: "pb-solar",
      clientId,
      name: "Wholesale solar supply",
      description: "Qualify installer/dealer equipment orders",
      appliesTo: "Solar equipment",
      trigger: { keywords: ["solar", "inverter", "panel", "battery", "wholesale"] },
      fields: [
        {
          id: "f1",
          label: "Customer type",
          internalKey: "customer_type",
          type: "SINGLE_SELECT",
          required: true,
          possibleValues: ["Installer", "Dealer", "Homeowner", "Other"],
          validation: null,
          agentQuestionGuidance: "Ask whether they install professionally or are looking for a home system.",
          crmMapping: "project_type",
          priority: 1,
          conditional: null,
        },
        {
          id: "f2",
          label: "What they need",
          internalKey: "customer_need",
          type: "TEXT",
          required: true,
          possibleValues: [],
          validation: null,
          agentQuestionGuidance: "Ask what equipment they need. Do not ask for exact wattage unless they know it.",
          crmMapping: "customer_need",
          priority: 2,
          conditional: null,
        },
        {
          id: "f3",
          label: "Needs installation",
          internalKey: "needs_installation",
          type: "BOOLEAN",
          required: false,
          possibleValues: ["Yes", "No"],
          validation: null,
          agentQuestionGuidance: "Only if they sound like a homeowner.",
          crmMapping: null,
          priority: 3,
          conditional: null,
        },
        {
          id: "f4",
          label: "Installation location",
          internalKey: "installation_location",
          type: "LOCATION",
          required: true,
          possibleValues: [],
          validation: null,
          agentQuestionGuidance: "Ask the site location.",
          crmMapping: "location",
          priority: 4,
          conditional: { field: "needs_installation", op: "equals", value: "Yes" },
        },
      ],
      completion: { requireAllRequired: true },
      dealReadiness: {},
      enabled: true,
      sortOrder: 0,
      updatedAt: new Date().toISOString(),
    },
    {
      id: "pb-machinery",
      clientId,
      name: "Excavator hire",
      description: "Machinery hire qualification",
      appliesTo: "Plant hire",
      trigger: { keywords: ["excavator", "hire", "crane", "bulldozer"] },
      fields: [
        {
          id: "m1",
          label: "Machine",
          internalKey: "machine",
          type: "SINGLE_SELECT",
          required: true,
          possibleValues: ["Excavator", "Crane", "Bulldozer", "Loader"],
          validation: null,
          agentQuestionGuidance: "Confirm the machine they need.",
          crmMapping: "customer_need",
          priority: 1,
          conditional: null,
        },
        {
          id: "m2",
          label: "Hire or purchase",
          internalKey: "hire_or_purchase",
          type: "SINGLE_SELECT",
          required: true,
          possibleValues: ["Hire", "Purchase"],
          validation: null,
          agentQuestionGuidance: "Ask if this is hire or purchase.",
          crmMapping: "project_type",
          priority: 2,
          conditional: null,
        },
        {
          id: "m3",
          label: "Hire duration",
          internalKey: "hire_duration",
          type: "TEXT",
          required: true,
          possibleValues: [],
          validation: null,
          agentQuestionGuidance: "Ask how long they need the machine.",
          crmMapping: "timeline",
          priority: 3,
          conditional: { field: "hire_or_purchase", op: "equals", value: "Hire" },
        },
      ],
      completion: { requireAllRequired: true },
      dealReadiness: {},
      enabled: true,
      sortOrder: 1,
      updatedAt: new Date().toISOString(),
    },
  ];

  const serviceAreas: ServiceArea[] = [
    {
      id: "sa-harare",
      label: "Harare",
      country: "Zimbabwe",
      province: "Harare",
      city: "Harare",
      region: null,
      radiusKm: null,
      serviceCategory: "Delivery",
      status: "PRIMARY",
      travelChargeApplies: false,
      travelChargeNote: null,
      minOrder: null,
      managerConfirmationRequired: false,
      assignedNote: null,
      active: true,
    },
    {
      id: "sa-mutare",
      label: "Mutare",
      country: "Zimbabwe",
      province: "Manicaland",
      city: "Mutare",
      region: null,
      radiusKm: null,
      serviceCategory: "Delivery",
      status: "CONFIRMATION_REQUIRED",
      travelChargeApplies: true,
      travelChargeNote: "Transport outside Harare is quoted separately",
      minOrder: null,
      managerConfirmationRequired: true,
      assignedNote: "Sales team",
      active: true,
    },
    {
      id: "sa-borrowdale",
      label: "Borrowdale",
      country: "Zimbabwe",
      province: "Harare",
      city: "Harare",
      region: "Borrowdale",
      radiusKm: null,
      serviceCategory: "Delivery",
      status: "PRIMARY",
      travelChargeApplies: false,
      travelChargeNote: null,
      minOrder: null,
      managerConfirmationRequired: false,
      assignedNote: null,
      active: true,
    },
  ];

  return {
    settings,
    exists: true,
    idealCustomers: customers,
    playbooks,
    stageGuidance: [
      {
        id: "sg-1",
        stage: "SCOPING",
        guidance: "Wholesale orders can be quoted from catalogue once qualification is complete. Do not offer site installation visits.",
        preconditions: [],
      },
    ],
    serviceAreas,
    appointmentTypes: [
      {
        id: "ap-1",
        name: "Sales call",
        durationMinutes: 30,
        eligibleUserIds: ["user-1"],
        workingHoursSource: "COMPANY",
        customWorkingDays: null,
        customStartTime: null,
        customEndTime: null,
        minNoticeHours: 2,
        locationRequired: false,
        bufferMinutes: 0,
        enabled: true,
        sortOrder: 0,
      },
    ],
    faqs: [
      {
        id: "faq-1",
        question: "Do you offer installation?",
        approvedAnswer:
          "We supply solar equipment wholesale to installers and dealers. We do not provide residential installation — we can help you with the equipment and introduce you to a local installer if useful.",
        aliases: ["Can you install it?", "Do you fit solar?", "Do you do installation?"],
        category: "Installation",
        active: true,
        productIds: [],
        lastReviewedAt: new Date().toISOString(),
        reviewerId: null,
        version: 1,
        updatedAt: new Date().toISOString(),
      },
    ],
    examples: [],
    rules: [
      {
        id: "r-1",
        ruleType: "NEVER_SAY",
        text: "Never promise same-day delivery.",
        structuredKey: null,
        enabled: true,
      },
      {
        id: "r-2",
        ruleType: "NEVER_DO",
        text: "Never apply discounts.",
        structuredKey: "NEVER_APPLY_DISCOUNT",
        enabled: true,
      },
      {
        id: "r-3",
        ruleType: "NEVER_DO",
        text: "Never give technical troubleshooting.",
        structuredKey: "NEVER_TROUBLESHOOT",
        enabled: true,
      },
    ],
    escalationRules: [
      {
        id: "esc-1",
        name: "Discount over 5%",
        conditionKey: "DISCOUNT_REQUEST",
        conditionConfig: { minPercent: 5 },
        destinationType: "SALES_MANAGER",
        destinationId: null,
        priority: "HIGH",
        customerMessage:
          "I want to make sure this is handled correctly, so I'm bringing a member of the team into the conversation.",
        enabled: true,
      },
    ],
    knowledgeDocuments: [
      {
        id: "doc-old-warranty",
        title: "2024 Warranty Brochure",
        category: "WARRANTY",
        description: "Outdated brochure",
        storageKey: null,
        contentText: "This inverter has a 10-year warranty.",
        status: "APPROVED",
        version: 1,
        uploadedById: null,
        lastReviewedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 340).toISOString(),
        effectiveDate: null,
        expiresAt: null,
        approvedById: null,
        approvedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    canonical: {
      companyName: "SunGrid Wholesale",
      industry: "Solar",
      timezone: "Africa/Harare",
      website: "https://sungrid.example",
      phone: "+263 4 000 000",
      email: "sales@sungrid.example",
      address: "Harare",
      country: "Zimbabwe",
      productCount: 12,
      serviceCount: 0,
      packageCount: 2,
      quoteTemplateCount: 1,
      currency: "USD",
      paymentTerms: "100% before dispatch",
      allowQuotationDiscount: false,
      priceEditPolicy: "standard_only",
      hasOperatingHoursRow: true,
      workingDays: [1, 2, 3, 4, 5, 6],
      workStartTime: "08:00",
      workEndTime: "17:00",
      hasQualificationFlow: false,
      teamUserCount: 3,
      agentAutonomyMode: "COPILOT",
      quoteAutoSendLimit: null,
    },
  };
}
